#
# Global variables for all nodes
#
---

#If set to true it will reset the K8S cluster on each run
K8S_RESET: false

# Kubernetes version
K8S_VERSION: "{{ '1.14*' if production else '1.13*'}}"

#kubeadm options
KUBEADM_OPTS_INIT: #  "--ignore-preflight-errors=SystemVerification" #Ignore btrfs
KUBEADM_APISERVER_HOST: "{{ 'k8s-api.angelnu.com' if production else 'k8s-test-api.angelnu.com' }}"
KUBEADM_APISERVER_IP:   "{{ '192.168.2.201'       if production else '192.168.2.203'            }}"
KUBEADM_APISERVER_PORT: 6443
KUBEADM_NODE_PORTRANGE: 30000-32000
KUBEADM_CFG: /etc/kubernetes/kubeadmcfg.yaml

#Kubelet options
KUBELET_OPTS: " --allow-privileged=true"

# Kubernetes dashboard
#K8S_DASHBOARD_IMAGE: angelnu/kubernetes-dashboard:v1.10.0

timezone: "Europe/Berlin"
ssh:
  pub_key_path: "~/.ssh/id_rsa.pub"
PACKAGES:
  - docker-ce=5:18.09.*
  - kubeadm={{ K8S_VERSION }}
  - kubelet={{ K8S_VERSION }}
  - kubectl={{ K8S_VERSION }}
  - rsync
  - glusterfs-client
  - nfs-common
  - attr
  - conntrack
  - vim
PACKAGES2REMOVE:
  - zram-config
  - sendmail-base
  - libnss-mdns #It uses multicast dns to resol .local -> conflicts with k8s dns names: https://askubuntu.com/questions/81797/nslookup-finds-ip-but-ping-doesnt



# Generated
KUBELET_PRIMARY_MASTER_HOSTNAME: "{{ groups['masters'][0] }}"

#Local K8S files
K8S_LOCAL_KUBELET_CFG_PATH: "{{ './kubeconfig' if production else './kubeconfig-test' }}"

#K8S files in the server
K8S_ETC_PATH: /etc/kubernetes
K8S_KUBELET_CFG_PATH: /etc/kubernetes/kubelet.conf
K8S_ADMIN_CFG_PATH: /etc/kubernetes/admin.conf

#Environment varibles for kubectl
KUBECTL_ENV:
  KUBECONFIG: "{{K8S_ADMIN_CFG_PATH}}"

#Environment varibles for kubectl
LOCAL_KUBECTL_ENV:
  KUBECONFIG: "{{ K8S_LOCAL_KUBELET_CFG_PATH }}/admin.conf"
