#Install depencies before running this script
#Expect that user anunez exists
# - apt-get install openssh-server python vim
# - ip add add 192.168.2.3
# - allow ssh as root -> uncomment "PermitRootLogin prohibit-password" in "/etc/ssh/sshd_config"
# - ssh-copy-id then "cp -a /home/anunez/.ssh /root;chown -R root:root /root/.ssh"
- name: Setup HW to run Kubernetes
  hosts: all

  tasks:
    - import_role: name=hw_setup
