#Install depencies before running this script
#Expect that user anunez exists
# - apt-get install openssh-server python vim
# - ip add add 192.168.2.3
# - allow ssh as root -> uncomment "PermitRootLogin prohibit-password" in "/etc/ssh/sshd_config"
# - ssh-copy-id then "cp -a /home/anunez/.ssh /root;chown -R root:root /root/.ssh"
- name: Install Intel Server
  hosts: server.home.angelnu.com
  become: true

  tasks:
  - name: Install Packages
    apt:
      name: "{{ item }}"
      force: yes
      state: present
    with_items:
    - ubuntu-desktop
    - btrfs-progs

  - name: "Create fix network IP"
    copy:
      dest: /etc/netplan/fixIP.yaml
      content: |
        # This file describes the network interfaces available on your system
        # For more information, see netplan(5).
        network:
          version: 2
          renderer: networkd
          ethernets:
            eno1:
              match:
                name: en*
              dhcp4: yes
              dhcp6: yes
              addresses: [192.168.2.3/24]
              gateway4: 192.168.2.1
              nameservers:
                search: [fritz.box]
                addresses: [192.168.2.1, 9.9.9.9]
    register: result

- name: Setup Systems to run Kubernetes
  hosts: all

  tasks:
    - import_role: name=setup
