- name: "Resetting if required"
  hosts: nodes
  tasks:
    - import_role: name=k8s-reset-node
      when: K8S_RESET

- name: Kubernetes master configuration
  hosts: masters
  gather_facts: false #Already queried
  tasks:
    - import_role: name=k8s-master

- name: Add workers
  hosts: workers
  gather_facts: false #Already queried
  tasks:
    - import_role: name=k8s-worker

- name: Set K8S nodes (labels, services)
  hosts: nodes
  gather_facts: false #Already queried
  tasks:
    - import_role: name=k8s-initialized-node
