- name: Kubernetes primary master configuration
  hosts: masters[0]

  roles:
  - master-primary

- name: Kubernetes secundary masters configuration
  hosts: masters[1:]

  roles:
  - master-secundaries
