- name: Reset machine uuid
  hosts: all
  gather_facts: false
  tasks:
  - shell:
      sleep 1 && \
      rm -f /var/lib/dbus/machine-id && \
      rm -f /etc/machine-id && \
      dbus-uuidgen --ensure && \
      systemd-machine-id-setup && \
      cat /etc/machine-id
    register: result
  - debug:
      var: result.stdout
  serial: 1 #Serialise in order to have different timestamps. This also explains the sleep 1
            # Implementation here: https://dbus.freedesktop.org/doc/api/html/dbus-internals_8c_source.html#l00667
