- name: "Resetting if required"
  hosts: nodes
  tasks:
    - import_role: name=reset
      when: K8S_RESET

- name: Kubernetes master configuration
  hosts: masters
  gather_facts: false #Already queried
  tasks:
    - import_role: name=master

- name: Add workers
  hosts: workers
  gather_facts: false #Already queried
  tasks:
    - import_role: name=workers

- name: Update all kubernetes services
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
  - import_role: name=load-services
