- name: "Resetting if required"
  hosts: workers
  tasks:
    - import_role: name=reset
      when: K8S_RESET

- name: Add workers
  hosts: workers
  gather_facts: false #Already queried
  tasks:
    - import_role: name=workers
