- name: Adding node to cluster
  shell: kubeadm join {{KUBEADM_OPTS| default('')}} --token {{ token }} --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,Port-10250 --discovery-token-unsafe-skip-ca-verification --node-name={{inventory_hostname}} {{ master }}:6443

- import_tasks: ../master-settle/main.yaml

# - name: Push kubernetes Certificates - {{K8S_ETC_PATH}}
#   synchronize:
#     dest: "{{K8S_ETC_PATH}}"
#     src: "./kubeconfig/pki"
#
# - name: Generate script for adapting the copied files in /etc/kubernetes for the respective master host
#   template: src=adapt-etc-kubernetes.sh.j2 dest=/root/adapt-etc-kubernetes.sh
#
# - name: Adapt IP addresses in /etc/kubernetes to respective master host
#   command: sh /root/adapt-etc-kubernetes.sh


- import_tasks: etcd.yaml


- name: Mark node as master
  shell: "kubeadm alpha phase mark-master --node-name {{inventory_hostname}}"
  environment: "{{kube_cfg_env}}"
  delegate_to: "{{master}}"

- import_tasks: ../master-settle/main.yaml
