- name: Stop kubelet
  service: name=kubelet enabled=yes state=stopped

- name: Push kubernetes configuration - {{K8S_ETC_PATH}}
  synchronize:
    dest: "{{K8S_ETC_PATH}}"
    src: "./kubeconfig/"

- name: Generate script for adapting the copied files in /etc/kubernetes for the respective master host
  template: src=adapt-etc-kubernetes.sh.j2 dest=/root/adapt-etc-kubernetes.sh

- name: Adapt IP addresses in /etc/kubernetes to respective master host
  command: sh /root/adapt-etc-kubernetes.sh

- import_tasks: etcd.yaml

- name: Delete unneeded files copied from primary master
  shell: rm {{K8S_ETC_PATH}}/pki/ca.crt {{K8S_ETC_PATH}}/kubelet.conf

- name: Adding node to cluster
  shell: kubeadm join --token {{ token }} --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,Port-10250 --discovery-token-unsafe-skip-ca-verification --node-name={{inventory_hostname}} {{ master }}:6443

- name: Mark node as master
  shell: "kubeadm alpha phase mark-master --node-name {{inventory_hostname}}"
  environment: "{{kube_cfg_env}}"
  delegate_to: "{{master}}"
