- name: Reset Kubernetes installation
  shell: "kubeadm reset"
  when: k8s_reset

- name: Check Kubelet config file - {{kubelet_cfg_path}}
  stat:
    path: "{{kubelet_cfg_path}}"
  register: kubelet_st

- name: Initalizing secundary Kubernetes master
  block:
    - import_tasks: init.yaml
      when: kubelet_st.stat.exists == False
  rescue:
    - name: Error initializing -> reset cluster
      shell: "kubeadm reset"
    - fail:
        msg: Partitially initisalised cluster deleted. Terminating now.
