- name: "Run tasks for primary"
  include_tasks: primary.yaml
  when: inventory_hostname == KUBELET_PRIMARY_MASTER_HOSTNAME

- name: "Run tasks for secundaries"
  include_tasks: secundary.yaml
  when: inventory_hostname != KUBELET_PRIMARY_MASTER_HOSTNAME

#Each master should connect to its own REST API server
- name: Set all nodes to use 127.0.0.1 for {{KUBEADM_APISERVER_HOST}}
  include_tasks: kubernetes_set_k8s_api.yaml
  vars:
    #KUBEADM_APISERVER_IP: "#Dissabled -> use {{ KUBEADM_APISERVER_HOST }}"
    KUBEADM_APISERVER_IP: 127.0.0.1

- name: Create .kube settings directory
  file:
    path: .kube
    state: directory

- name: Create symbolic link
  file:
    src: "{{K8S_ADMIN_CFG_PATH}}"
    dest: ".kube/config"
    state: link

#- name: "Dispatch tasks to master"
#  include_tasks: asWorker.yaml

- name: Deploy dashboard
  import_tasks: dashboard.yaml

- name: Create Docker settings directory
  file:
    path: .docker
    state: directory
