- name: Secondary - Get Kubernetes nodes
  include_tasks: kubernetes_get_nodes.yaml

- name: Secondary- Reset cluster if {{ KUBEADM_CFG }} changed
  shell:
    kubeadm reset -f #Do not use the full reset role to keep the certs
  when: inventory_hostname not in kubernetes_get_nodes_result.stdout

#Copy files
- name: Secondary - Create {{K8S_ETC_PATH}}/pki/etcd
  file:
    path: "{{K8S_ETC_PATH}}/pki/etcd"
    state: directory

- name: Secondary - Upload etcd certs
  synchronize:
    dest: "{{K8S_ETC_PATH}}/pki/etcd/"
    src: "{{ K8S_LOCAL_KUBELET_CFG_PATH }}/{{ item }}"
  with_items:
    - pki/etcd/ca.crt
    - pki/etcd/ca.key

- name: Secondary - Upload kube certs
  synchronize:
    dest: "{{K8S_ETC_PATH}}/pki/"
    src: "{{ K8S_LOCAL_KUBELET_CFG_PATH }}/{{ item }}"
  with_items:
    - pki/sa.pub
    - pki/sa.key
    - pki/ca.crt
    - pki/ca.key
    - pki/front-proxy-ca.crt
    - pki/front-proxy-ca.key

#Actual join
- name: "Secondary - join nodes"
  include_tasks: kubernetes_join_node.yaml
  vars:
    node_admin: True
