- name: Get Kubernetes nodes
  include_tasks: kubernetes_get_nodes.yaml

- name: Reset cluster if {{ KUBEADM_CFG }} changed
  shell:
    kubeadm reset -f
  #we cannot reset here for master or we will loose certs
  when: not node_admin and inventory_hostname not in kubernetes_get_nodes_result.stdout

- name: Get Kubernetes token
  include_tasks: kubernetes_get_token.yaml
  when: inventory_hostname not in kubernetes_get_nodes_result.stdout
  #we must always run this (need output bellow)

#- include_tasks: kubernetes_set_k8s_api.yaml
#  vars:
#    KUBEADM_APISERVER_IP: "{{hostvars[groups['masters'][0]].ansible_default_ipv4.address}}"
#  when: ansible_hostname not in kubernetes_get_nodes_result.stdout

- name: Join node
  shell:
    kubeadm join
      --token {{kubernetes_token.stdout}}
      --node-name={{inventory_hostname}}
      --discovery-token-ca-cert-hash sha256:{{kubernetes_ca_cert_hash.stdout}}
      {{ '--control-plane' if node_admin else '' }}
      {{ KUBELET_PRIMARY_MASTER_HOSTNAME }}:{{ KUBEADM_APISERVER_PORT }}
  register: result
  changed_when: result.stdout_lines | length
  when: inventory_hostname not in kubernetes_get_nodes_result.stdout
  # serial: 1 would be the proper solution here, but that can only be set on play level
  # upstream issue: https://github.com/ansible/ansible/issues/12170
  #run_once: true
  #with_items: "{{ansible_play_batch}}"
  #delegate_to: "{{item}}"

- wait_for: port={{ KUBEADM_APISERVER_PORT }}
  when: node_admin

- uri:
    url: https://localhost:{{ KUBEADM_APISERVER_PORT }}
    status_code: 403
    timeout: 60
    validate_certs: False
  register: result
  until: result is not failed
  retries: 60
  delay: 5
  changed_when: false
  when: node_admin

- name: Settle nodes
  include_tasks: kubernetes_node_settle.yaml
