# ------------------- nas ------------------- #

kind: "Service"
apiVersion: "v1"
metadata:
  name: nas
spec:
  type: ExternalName
  #Bug: externalName: nas.home.angelnu.com
  externalName: 192.168.2.10
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nas
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: nas.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nas
          servicePort: https
  - host: nas.nunez-gregoire.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: nas
          servicePort: https
