kind: "Service"
apiVersion: "v1"
metadata:
  name: printer
spec:
  type: ExternalName
  externalName: 192.168.2.7
  ports:
  - name: http
    protocol: TCP
    port: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: printer
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16"
spec:
  rules:
  - host: print.home.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: printer
          servicePort: http
