kind: "Service"
apiVersion: "v1"
metadata:
  name: wifi
spec:
  type: ExternalName
  externalName: 192.168.2.47
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wifi
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16"
spec:
  rules:
  - host: wifi.home.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wifi
          servicePort: https
