apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account
  namespace: kube-system
  labels:
    glusterfs: heketi-sa
    heketi: sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heketi-sa-view
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  namespace: default
  name: heketi-service-account
