apiVersion: v1
kind: ConfigMap
metadata:
  name: heketi-config-secret
  namespace: kube-system
data:
  all.json: |+
    {
      "clusters": [
        {
          "nodes": [
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "n10.angelnu.com"
                  ],
                  "storage": [
                    "192.168.2.86"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/mnt/host-dev/sda4"
              ]
            },
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "n11.angelnu.com"
                  ],
                  "storage": [
                    "192.168.2.87"
                  ]
                },
                "zone": 2
              },
              "devices": [
                "/mnt/host-dev/sda4"
              ]
            },
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "n9.angelnu.com"
                  ],
                  "storage": [
                    "192.168.2.84"
                  ]
                },
                "zone": 3
              },
              "devices": [
                "/mnt/host-dev/sda4"
              ]
            }
          ]
        }
      ]
    }
