- name: Update system (after refreshing caches)
  apt:
    update_cache: yes
    cache_valid_time: 600
    upgrade: yes
    autoremove: true
  register: result

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: result | changed

- name: Waiting for servers
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
