apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccu
spec:
  selector:
    matchLabels:
      app: ccu
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      name: ccu
      labels:
        app: ccu
    spec:
      hostname: ccu
      nodeSelector:
        beta.kubernetes.io/arch: arm
        hmip: "true"
      containers:
      - name: ccu
        image: angelnu/ccu:3
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "130Mi"
            cpu: "100m"
          limits:
            #memory: "128Mi"
            #cpu: "500m"
        env:
          - name: PERSISTENT_DIR
            value: "/mnt"
          - name: CHECK_PERSISTENT_DIR
            value: "y"
        ports:
        ##ssh
        - containerPort: 22
        # web-ui
        - containerPort: 80
        # web-ui (HTTPS)
        - containerPort: 443
        # wired Homematic
        - containerPort: 2000
        # wireless Homematic (rfd)
        - containerPort: 2001
        # Homematic IP
        - containerPort: 2010
        # Rega
        - containerPort: 8081
        # livenessProbe:
        #   tcpSocket:
        #     port: 2001
        #   initialDelaySeconds: 600
        #   timeoutSeconds: 10
        volumeMounts:
        - mountPath: /mnt
          name: ccu-volume
        - mountPath: /dev
          name: dev-volume
        - mountPath: /sys
          name: sys-volume
      volumes:
        - name: ccu-volume
          glusterfs:
            endpoints: glusterfs-storage
            path: ccu2
        - name: dev-volume
          hostPath:
            path: /dev
            type: Directory
        - name: sys-volume
          hostPath:
            path: /sys
            type: Directory

---
# ------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    app: ccu
  name: ccu
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: rega
    port: 8181
    targetPort: 8181
  - name: hs485
    port: 2000
    targetPort: 2000
  - name: rfd
    port: 2001
    targetPort: 2001
  - name: hmip
    port: 2010
    targetPort: 2010
  type: NodePort
  selector:
    app: ccu


---
# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ccu
  annotations:
    ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16"
spec:
  rules:
  - host: homematic.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ccu
          servicePort: http
