# ------------------- CronJob ------------------- #
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloud-automated-test
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: cloud-automated-test
        spec:
          containers:
          - name: cloud-automated-test
            image: ansible/ansible:default
            imagePullPolicy: Always
            env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            workingDir: /root
            command:
            - /bin/sh
            - -ecx
            - |
              trap 'exit' INT TERM
              cp -av .sshro .ssh
              ssh-keyscan github.com > /root/.ssh/known_hosts
              git clone --recursive https://github.com/angelnu/homecloud.git

              echo "Install dependencies"
              #Ansible
              pip install ansible jmespath
              #Kubectl repo
              apt-get update && apt-get install -y apt-transport-https
              curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
              echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
              #tools
              apt update;apt install -y rsync kubectl

              echo "Run regression"
              cd homecloud
              ./bin/test_all.sh

            volumeMounts:
            - name: ssh-key-volume
              mountPath: "/root/.sshro"
          restartPolicy: Never
          volumes:
          - name: ssh-key-volume
            secret:
              secretName: git-ssh-keys
              defaultMode: 0700
---
# ------------------- Test Job ------------------- #
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: cloud-manual-test
  name: cloud-manual-test
spec:
  serviceName: cloud-manual-test
  # changing replicas value will require a manual etcdctl member remove/add
  # command (remove before decreasing and add after increasing)
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: cloud-manual-test
      labels:
        app: cloud-manual-test
    spec:
      restartPolicy: Always
      containers:
      - name: cloud-manual-test
        image: python
        imagePullPolicy: Always
        resources:
          requests:
            memory: "5Mi"
            cpu: "2m"
          limits:
            #memory: "128Mi"
            #cpu: "500m"
        env:
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        workingDir: /root
        command:
        - /bin/sh
        - -c
        - |
          trap 'exit' INT TERM
          cp -av .sshro .ssh
          ssh-keyscan github.com > /root/.ssh/known_hosts
          git clone --recursive https://github.com/angelnu/homecloud.git

          echo "Install dependencies"
          #Ansible
          pip install ansible jmespath
          #Kubectl repo
          apt-get update && apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
          #tools
          apt update;apt install -y rsync kubectl

          echo "Infinite sleep"
          while [ 1 ]; do
            sleep 600 &
            wait $!
          done
        volumeMounts:
        - name: ssh-key-volume
          mountPath: "/root/.sshro"
      volumes:
      - name: ssh-key-volume
        secret:
          secretName: git-ssh-keys
          defaultMode: 0700
