apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jackett
spec:
  serviceName: jackett
  selector:
    matchLabels:
      app: jackett
  replicas: 1
  template:
    metadata:
      name: jackett
      labels:
        app: jackett
    spec:
      hostname: jackett
      nodeSelector: #Only schedule in the big server
        kubernetes.io/hostname: server.home.angelnu.com
      containers:
      - name: jackett
        image: angelnu/jackett
        imagePullPolicy: Always
        resources:
          requests:
            memory: "115Mi"
            cpu: "800m"
          limits:
            #memory: "128Mi"
            #cpu: "500m"
        livenessProbe:
          exec:
            command:
            - wget #no ping in this container
            - rss.angelnu.com
          initialDelaySeconds: 60
          periodSeconds: 300
          failureThreshold: 2
        ports:
        - containerPort: 9117
        env:
        - name: TZ
          value: Europe/Berlin
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: jackett/config
        - mountPath: /downloads
          name: data
          subPath: downloaders/transmission
# VPN boiler-plate 1 (insert at the end of volumeMounts)
        - name: resolv
          mountPath: /etc/resolv.conf
          subPath: resolv.conf
      - name: vxlan
        image: angelnu/openvpn-helper
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: resolv
          mountPath: /etc_shared
# end of VPN boiler-plate 1
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-kubernetes
      - name: data
        flexVolume:
          driver: "angelnu/cifs"
          secretRef:
            name: "cifs-secret"
          options:
            source: "//nas.home.angelnu.com/downloads"
            mountOptions: "dir_mode=0775,file_mode=0664,noperm"

# VPN boiler-plate 2 (append at the end of the volumes section)
      - name: resolv
        emptyDir: {}
      initContainers:
      - name: init-vxlan
        image: angelnu/openvpn-helper
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: FIRST_BOOT
          value: "true"
        volumeMounts:
        - name: resolv
          mountPath: /etc_shared
# end of VPN boiler-plate 2

---
# -------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    app: jackett
  name: jackett
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 9117
  selector:
    app: jackett
---

# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jackett
  annotations:
    ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16"
spec:
  rules:
  - host: search.home.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jackett
          servicePort: http
