apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  serviceName: nextcloud
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1
  template:
    metadata:
      name: nextcloud
      labels:
        app: nextcloud
    spec:
      hostname: nextcloud
      nodeSelector: #Only schedule in the big server
        kubernetes.io/hostname: server.angelnu.com
      containers:
      - name: nextcloud
        image: ownyourbits/nextcloudpi:latest
        imagePullPolicy: Always
        args:
        - nextcloud.angelnu.com
        resources:
          requests:
            memory: "200Mi"
            cpu: "20m"
          limits:
            #memory: "128Mi"
            #cpu: "500m"
        ports:
        - containerPort: 443
        - containerPort: 80
        - containerPort: 4443 #admin console
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 60 # 1 minute
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 5 # 5 minutes
        volumeMounts:
        - mountPath: /data
          name: nextcloud-data
          subPath: nextcloud
        # - mountPath: /software
        #   name: software
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nfs-kubernetes
        # - name: software
        #   flexVolume:
        #     driver: "angelnu/cifs"
        #     secretRef:
        #       name: "cifs-secret"
        #     options:
        #       source: "//nas.home.angelnu.com/software"
        #       mountOptions: "dir_mode=0755,file_mode=0644,noperm"

---
# -------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.2.231
  selector:
    app: nextcloud

---
# -------------------- Admin Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    app: nextcloud
  name: nextcloud-admin
spec:
  ports:
  - name: https
    port: 443
    targetPort: 4443
  selector:
    app: nextcloud

---

# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: nextcloud.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud-home
  annotations:
    ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16"
spec:
  rules:
  - host: nextcloud.home.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: https
  - host: nextcloud-admin.home.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud-admin
          servicePort: https
