apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  serviceName: plex
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      name: plex
      labels:
        app: plex
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name":"macvlan-static",
            "ips": ["192.168.1.2"]
          }]
    spec:
      #hostNetwork: true
      hostname: plex
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: plex
        image: plexinc/pms-docker:plexpass
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "500Mi"
            #cpu: "100m"
          limits:
            #memory: "128Mi"
            #cpu: "500m"

        ports:
        - containerPort: 32400
        - containerPort: 3005
        - containerPort: 8324
        - containerPort: 32469
        - containerPort: 1900
          protocol: UDP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        env:
        - name: TZ
          value: Europe/Berlin
        - name: ALLOWED_NETWORKS
          value: 192.168.1.0/16
        volumeMounts:
        - mountPath: /dev/dri
          name: dri
        - mountPath: /config
          name: config
          subPath: plex/config
        - mountPath: /downloads
          name: downloads
        - mountPath: /videos
          name: videos
        # - mountPath: /music
        #   name: music
      volumes:
      - name: dri
        hostPath:
          path: /dev/dri
      - name: config
        persistentVolumeClaim:
          claimName: nfs-kubernetes
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads
        # flexVolume:
        #   driver: "angelnu/cifs"
        #   secretRef:
        #     name: "cifs-secret"
        #   options:
        #     source: "//nas.home.angelnu.com/downloads"
        #     mountOptions: "dir_mode=0775,file_mode=0664,noperm"
      - name: videos
        persistentVolumeClaim:
          claimName: nfs-video
        # flexVolume:
        #   driver: "angelnu/cifs"
        #   secretRef:
        #     name: "cifs-secret"
        #   options:
        #     source: "//nas.home.angelnu.com/video"
        #     mountOptions: "dir_mode=0775,file_mode=0664,noperm"
      # - name: music
      #   flexVolume:
      #     driver: "angelnu/cifs"
      #     secretRef:
      #       name: "cifs-secret"
      #     options:
      #       source: "//nas.home.angelnu.com/music"
      #       mountOptions: "dir_mode=0775,file_mode=0664,noperm"
---
# -------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: plex
  name: plex
spec:
  ports:
  - name: http
    port: 32400
    targetPort: 32400
    protocol: TCP
  - name: tbd1
    port: 3005
    targetPort: 3005
    protocol: TCP
  - name: tbd2
    port: 8324
    targetPort: 8324
    protocol: TCP
  - name: tbd3
    port: 32469
    targetPort: 32469
    protocol: TCP
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 192.168.1.133
  sessionAffinity: ClientIP
---
# -------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: plex-udp
  name: plex-udp
spec:
  ports:
  - name: tbd4
    port: 1900
    targetPort: 1900
    protocol: UDP
  - name: tbd5
    port: 32410
    targetPort: 32410
    protocol: UDP
  - name: tbd6
    port: 32412
    targetPort: 32412
    protocol: UDP
  - name: tbd7
    port: 32413
    targetPort: 32413
    protocol: UDP
  - name: tbd8
    port: 32414
    targetPort: 32414
    protocol: UDP
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 192.168.1.133
  sessionAffinity: ClientIP
---

# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
spec:
  tls:
  - hosts:
    - plex.angelnu.com
    secretName: prod-wildcard-angelnu-com-tls
  rules:
  - host: plex.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: http
