kind: "Service"
apiVersion: "v1"
metadata:
  name: server
spec:
  type: ExternalName
  externalName: home.angelnu.com
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: plex
    protocol: TCP
    port: 32400
    targetPort: 32400

---
kind: "Service"
apiVersion: "v1"
metadata:
  name: server-plex
spec:
  type: ExternalName
  externalName: 192.168.2.3
  ports:
  - name: plex
    protocol: TCP
    port: 32400
    targetPort: 32400


---
# ------------------- server-appache ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server
spec:
  rules:
  - host: nextcloud.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: server
          servicePort: 443
  - host: rss.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: server
          servicePort: 443
  - host: plex.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: server-plex
          servicePort: 32400

---
# ------------------- nas ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nas
spec:
  rules:
  - host: nas.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nas
          servicePort: 443
