apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: armhf/alpine:latest
    command:
      - sh
      - -c
      - while [ 1 ]; do sleep 10;done
    ports:
    - containerPort: 22
    volumeMounts:
    - mountPath: /gluster
      name: gluster-volume
  volumes:
    - name: gluster-volume
      glusterfs:
        endpoints: glusterfs-storage
        path: shared01
