---
# ------------------- Deployment ------------------- #

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ttrss
  labels:
    app: ttrss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ttrss
  template:
    metadata:
      labels:
        app: ttrss
    spec:
      containers:
      - name: ttrss
        image: angelnu/ttrss-arm
        env:
        - name: TTRSS_PROTO
          value: https
        - name: TTRSS_URL
          value: rss.angelnu.com
        - name: TTRSS_PORT
          value: ""

        - name: DB_HOST
          value: ttrss-postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: ttrss-postgres-secret
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ttrss-postgres-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: ttrss-postgres-secret
              key: password
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 600 # 10 minutes
          timeoutSeconds: 10
          failureThreshold: 12 # 2 minutes

---
# -------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    app: ttrss
  name: ttrss
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: ttrss
---

# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ttrss
  annotations:
    traefik.frontend.priority: "1"
spec:
  rules:
  - host: rss.angelnu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ttrss
          servicePort: http
