- name: Wait for apiserver to be restarted
  shell: kubectl get nodes
  environment: "{{kube_cfg_env}}"
  register: result
  until: result|succeeded
  retries: 60
  delay: 5

- name: Wait for node to be ready
  shell: kubectl get nodes | grep {{inventory_hostname}}
  environment: "{{kube_cfg_env}}"
  register: result
  until: result|succeeded and "NotReady" not in result.stdout
  retries: 60
  delay: 5
