- name: Load all services to cluster
  shell: "kubectl apply -R -f  services"
  delegate_to: localhost
  environment: "{{ LOCAL_KUBECTL_ENV }}"
  register: result
  vars:
    queryStr: "status.conditions[?reason=='KubeletReady'].status"
  changed_when:
  - "'unchanged'  not in result.stdout| join('')"
  - "'configured' not in result.stdout| join('')"
  run_once: True
