- name: Set labels
  shell: >
    kubectl label nodes {{inventory_hostname}} --overwrite
    {% for key,value in k8s_labels.items() %}
      {{ key }}={{ value }} \
    {% endfor %}
  delegate_to: localhost
  environment: "{{ LOCAL_KUBECTL_ENV }}"
  register: result
  changed_when:
  - "'not labeled'  not in result.stdout| join('')"
