- name: Set taints
  shell: >
    kubectl taint nodes {{inventory_hostname}}
    {% for key,value in k8s_taints.items() %}
      {{ key }}=true:{{ value }} \
    {% endfor %}
  delegate_to: localhost
  environment: "{{ LOCAL_KUBECTL_ENV }}"
  register: result
  when: k8s_taints is defined
  changed_when:
  - "'taint(s) with same effect(s)'  not in result.stdout| join('')"
