- name: Reset Kubernetes installation
  shell: "kubeadm reset; rm -rf {{KUBELET_CHECKPOINT_PATH}}"
  when: k8s_reset

- name: Check Kubelet config file - {{kubelet_cfg_path}}
  stat:
    path: "{{kubelet_cfg_path}}"
  register: kubelet_st

- name: Init Kubernetes cluster
  block:
    - import_tasks: init.yaml
      when: kubelet_st.stat.exists == False
  rescue:
    - name: Error initializing -> reset cluster
      shell: "echo kubeadm reset" #TBD: remove echo
    - fail:
        msg: Partitially initisalised cluster deleted. Terminating now.

- name: Download kubernetes configuration - {{K8S_ETC_PATH}}
  synchronize:
    mode: pull
    src: "{{K8S_ETC_PATH}}/"
    dest: "./kubeconfig"

- name: Deploy dashboard
  import_tasks: dashboard.yaml
