- name: Delete old join tokens
  shell:
    kubeadm token list|tail -n +2|cut -d' ' -f1|xargs -r kubeadm token delete
  delegate_to: "{{ KUBELET_PRIMARY_MASTER_HOSTNAME }}"

- name: Get join token
  shell:
    kubeadm token create
  delegate_to: "{{ KUBELET_PRIMARY_MASTER_HOSTNAME }}"
  register: token

- name: Join worker
  shell:
    kubeadm join
     --token {{token.stdout}}
     --node-name={{inventory_hostname}}
     --discovery-token-unsafe-skip-ca-verification
     {{ KUBEADM_APISERVER_EXTRAHOSTS }}:6443
