timezone: "Europe/Berlin"
ssh:
  pub_key_path: "~/.ssh/id_rsa.pub"
PACKAGES:
  - docker-ce=18.03.*
  - kubeadm=1.10*
  - rsync
  - glusterfs-client
  - nfs-common
  - attr
PACKAGES2REMOVE:
  - zram-config
  - sendmail-base
  - libnss-mdns #It uses multicast dns to resol .local -> conflicts with k8s dns names: https://askubuntu.com/questions/81797/nslookup-finds-ip-but-ping-doesnt
