apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for must-have services"
---
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: normal-priority
value: 1000
globalDefault: true
description: "This default priority"
---
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
description: "This priority class should be used for not so important services"
