#We need the host to resolv cluster IPs to allow glusterfs to work
# To avoid cicular dependencies we need to avoid using the host resol
# This will be needed until the kube-controller-manager runs as pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    ["192.168.2.1"]
