apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "macvlan-static",
      "type": "macvlan",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "static",
        "subnet": "192.168.0.0/19",
        "rangeStart": "192.168.1.0",
        "rangeEnd": "192.168.1.63",
        "gateway": "192.168.2.1"
      }
    }'