apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kubernetes-kube-system
  namespace: kube-system
spec:
  storageClassName: nfs-kubernetes-kube-system
  capacity:
    storage: 18T
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.home.angelnu.com
    path: "/volume1/kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-kubernetes
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-kubernetes-kube-system"
  resources:
    requests:
      storage: 10T



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kubernetes
spec:
  storageClassName: nfs-kubernetes
  capacity:
    storage: 18T
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.home.angelnu.com
    path: "/volume1/kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-kubernetes
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-video
spec:
  capacity:
    storage: 18T
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas.home.angelnu.com
    path: "/volume1/video"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-video
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10T


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  capacity:
    storage: 18T
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas.home.angelnu.com
    path: "/volume1/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10T
