- name: "Run tasks for primary"
  include_tasks: primary.yaml
  when: inventory_hostname == KUBELET_PRIMARY_MASTER_HOSTNAME

- name: "Run tasks for secundaries"
  include_tasks: secundary.yaml
  when: inventory_hostname != KUBELET_PRIMARY_MASTER_HOSTNAME

- name: "Resolv {{ KUBEADM_APISERVER_HOST }} to localhost"
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 {{ KUBEADM_APISERVER_HOST }}

- name: Redeploy keepalived
  include_tasks: apiLoadBalancer.yaml
  vars:
    keepalive_rest_node: False

- name: "Dispatch tasks to master"
  include_tasks: asWorker.yaml

- name: Deploy dashboard
  import_tasks: dashboard.yaml
