- name: Primary - Init cluster
  shell:
    kubeadm init --config {{ KUBEADM_CFG }}
    creates="{{K8S_KUBELET_CFG_PATH}}"
  when: kubelet_st.stat.exists == False

- name: Primary - Adding network backend - Weave Net
  #shell: "kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.1.3/weave-daemonset.yaml"
  #shell: "kubectl apply -f https://cloud.weave.works/k8s/v1.7/net"
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  environment: "{{KUBECTL_ENV}}"

- name: Deploy dashboard
  import_tasks: dashboard.yaml

- name: Primary - Download {{K8S_ETC_PATH}}
  synchronize:
    mode: pull
    src: "{{K8S_ETC_PATH}}/"
    dest: "./kubeconfig"

- import_role: name=node-settle

- import_tasks: selfHost.yaml
  when: KUBELET_SELFHOST
