- name: Self-hosted Kubernetes cluster
  shell: kubeadm alpha phase selfhosting convert-from-staticpods

- name: "Enable apiserver checkpointing"
  shell: "kubectl -n kube-system annotate pods $(kubectl get pods -n kube-system | awk '/self-hosted-kube-apiserver/ {print $1;exit}') node.kubernetes.io/bootstrap-checkpoint='true'"
  environment: "{{KUBECTL_ENV}}"

- include_role: name=node-settle
