- name: Add apt-transport-https
  apt:
    name: 'apt-transport-https'
    state: present
    force: yes

- name: 'import Docker GPG signing key'
  apt_key:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg

- name: Add docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ ansible_distribution_release }} stable
    state: present

- name: Add Kubernetes Repo Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes Repo
  apt_repository:
    #repo: deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

#- name: Update system (after refreshing caches)
#  apt:
#    update_cache: yes
#    upgrade: safe

- name: Install Packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - docker-ce=17.09.1~ce-0~ubuntu
    - kubeadm
    - rsync
