- name: Set hostname
  hostname: name="{{ name }}"
  register: set_hostname

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ name }}"
  when: set_hostname.changed

- name: "Write timezone file with {{ timezone }}"
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
  register: result

- name: Enable new timezone
  shell: "timedatectl set-timezone {{ timezone }}"
  when: result | changed


- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent


- name: swap - disable swap
  shell: "cat /proc/swaps|tail -n +2 && swapoff --all"
  register: result
  changed_when: result.stdout_lines | length


- name: Comment out the dnsmask
  replace:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: '^dns=dnsmasq'
    replace: '#dns=dnsmasq'
  register: result

- name: Restart Network Manager
  systemd:
    name: network-manager
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: result.changed
