- name: Set hostname
  hostname: name="{{ name }}"
  register: set_hostname

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ name }}"
  when: set_hostname.changed

- name: Create timezone file
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
  register: result

- name: Enable new timezone
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: result | changed


- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent


- name: swap - disable swap
  command: swapoff --all
