- name: Add apt-transport-https
  apt:
    name: 'apt-transport-https'
    state: present
    force: yes

- name: 'import Docker GPG signing key'
  apt_key:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg

- name: Add docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ ansible_distribution_release }} stable
    state: present

- name: Add Glusterfs 5 PPA (Ubuntu)
  apt_repository:
    repo: ppa:gluster/glusterfs-5
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: 'import Glusterfs signing key'
  apt_key:
    url: http://download.gluster.org/pub/gluster/glusterfs/5/rsa.pub

- name: Add Glusterfs 5 repo (Debian)
  apt_repository:
    repo: deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ansible_distribution_major_version}}/{{'arm64' if 'arm' in ansible_architecture else 'amd64'}}/apt {{ ansible_distribution_release }} stable
    state: present
  when: ansible_distribution == 'Debian'

- name: Add Kubernetes Repo Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes Repo
  apt_repository:
    #repo: deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

#- name: Update system (after refreshing caches)
#  apt:
#    update_cache: yes
#    upgrade: safe

- name: Install Packages
  apt:
    name: "{{PACKAGES}}"
    force: yes
    state: present

- name: Remove Packages
  apt:
    name: "{{ PACKAGES2REMOVE }}"
    force: yes
    state: absent
