- name: Add and update packages
  import_tasks: apt.yaml

- name: Docker settings
  import_tasks: docker.yaml

- name: Setup system parameters (boot, hosts, timzone)
  import_tasks: system.yaml

- name: Setup network parameters
  import_tasks: network.yaml


# check if we need a reboot
- name: check if reboot needed
  stat: path=/var/run/reboot-required
  register: reboot_required_file

- name: Need reboot?
  when: reboot_required_file.stat.exists
  set_fact: need_reboot=True

#Reboot if needed at the end
- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: need_reboot | default(False)

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: need_reboot | default(False)
