# ------------------- Secret ------------------- #
apiVersion: v1
kind: Secret
metadata:
  name: ttrss-postgres-secret
data:
  # create with echo -n "admin" | base64
  dbname: dHQtcnNz #tt-rss
  username: dHQtcnNz #tt-rss
  password: cmVwbGFjZU1l #replaceMe
